### ISSUE TITLE
entropy_shrinkage, infinity case

### ISSUE THREAD

**Issue by tlienart** [cynddl/Discreet.jl#1]
https://github.com/cynddl/Discreet.jl/blob/master/src/entropy.jl#L45-#L50

```julia
# Regularization parameter
λ = (1 - sum(θ_ML .^ 2)) / ((n - 1) * sum((θ_ML - t_k) .^2))

isinf(λ) ?
  entropy(ProbabilityWeights(θ_ML)) :
  entropy(ProbabilityWeights(λ * t_k + (1 - λ) * θ_ML))
```

Numerically that could be a bit problematic right? Would it not make sense to do something like

```julia
if den < 1e-10
  return entropy(ProbabilityWeights(θ_ML))
else
  λ = (1 - sum(θ_ML .^ 2)) / den
  return entropy(ProbabilityWeights(λ * t_k + (1 - λ) * θ_ML))
end
```

all tests passing, d91295e20616419063e3bf616c7b92c3acd97cc7

**Comment by cynddl** [comment]
Thanks! I merged your PR #2 with the explicit check.
